//! 内置函数 Token ID 定义

/// 内置函数 Token ID
/// 每个内置函数对应一个唯一的整数 ID，用于快速匹配
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum BuiltinToken {
    // ========== 数学函数 (1-50) ==========
    Abs = 1,
    Sqr = 2,
    Sin = 3,
    Cos = 4,
    Tan = 5,
    Atn = 6,
    Log = 7,
    Exp = 8,
    Int = 9,
    Fix = 10,
    Round = 11,
    Rnd = 12,
    Sgn = 13,

    // ========== 类型转换函数 (51-100) ==========
    CStr = 51,
    CInt = 52,
    CLng = 53,
    CSng = 54,
    CDbl = 55,
    CBool = 56,
    CDate = 57,
    CByte = 58,
    CCur = 59,
    Hex = 60,
    Oct = 61,

    // ========== 字符串函数 (101-150) ==========
    Len = 101,
    Trim = 102,
    LTrim = 103,
    RTrim = 104,
    Left = 105,
    Right = 106,
    Mid = 107,
    UCase = 108,
    LCase = 109,
    InStr = 110,
    InStrRev = 111,
    StrComp = 112,
    Replace = 113,
    Split = 114,
    Join = 115,
    StrReverse = 116,
    Space = 117,
    String_ = 118,
    Asc = 119,
    Chr = 120,
    AscW = 121,
    ChrW = 122,
    LenB = 123,
    LeftB = 124,
    RightB = 125,
    MidB = 126,
    InStrB = 127,
    AscB = 128,
    ChrB = 129,

    // ========== 日期时间函数 (151-200) ==========
    Now = 151,
    Date = 152,
    Time = 153,
    Year = 154,
    Month = 155,
    Day = 156,
    Hour = 157,
    Minute = 158,
    Second = 159,
    WeekDay = 160,
    DateAdd = 161,
    DateDiff = 162,
    DatePart = 163,
    DateSerial = 164,
    DateValue = 165,
    TimeSerial = 166,
    TimeValue = 167,
    FormatDateTime = 168,
    MonthName = 169,
    WeekDayName = 170,
    Timer = 171,

    // ========== 数组函数 (201-220) ==========
    Array = 201,
    UBound = 202,
    LBound = 203,
    Filter = 204,
    IsArray = 205,

    // ========== 检验函数 (221-250) ==========
    IsNumeric = 221,
    IsDate = 222,
    IsEmpty = 223,
    IsNull = 224,
    IsObject = 225,
    IsNothing = 226,
    TypeName = 227,
    VarType = 228,

    // ========== 交互函数 (251-270) ==========
    MsgBox = 251,
    InputBox = 252,

    // ========== 其他函数 (271-300) ==========
    CreateObject = 271,
    GetObject = 272,
    Eval = 273,
    Execute = 274,
    RGB = 275,
    FormatCurrency = 276,
    FormatNumber = 277,
    FormatPercent = 278,
    ScriptEngine = 279,
    ScriptEngineMajorVersion = 280,
    ScriptEngineMinorVersion = 281,
    ScriptEngineBuildVersion = 282,
    Erase = 283,
    Escape = 284,
    Unescape = 285,
    IIf = 286,

    // 未知函数
    #[allow(dead_code)]
    Unknown = 0,
}

/// Token 注册表项
#[allow(dead_code)]
pub const TOKEN_REGISTRY: &[(&str, BuiltinToken)] = &[
    // 数学函数
    ("abs", BuiltinToken::Abs),
    ("sqr", BuiltinToken::Sqr),
    ("sin", BuiltinToken::Sin),
    ("cos", BuiltinToken::Cos),
    ("tan", BuiltinToken::Tan),
    ("atn", BuiltinToken::Atn),
    ("log", BuiltinToken::Log),
    ("exp", BuiltinToken::Exp),
    ("int", BuiltinToken::Int),
    ("fix", BuiltinToken::Fix),
    ("round", BuiltinToken::Round),
    ("rnd", BuiltinToken::Rnd),
    ("sgn", BuiltinToken::Sgn),
    // 类型转换函数
    ("cstr", BuiltinToken::CStr),
    ("cint", BuiltinToken::CInt),
    ("clng", BuiltinToken::CLng),
    ("csng", BuiltinToken::CSng),
    ("cdbl", BuiltinToken::CDbl),
    ("cbool", BuiltinToken::CBool),
    ("cdate", BuiltinToken::CDate),
    ("cbyte", BuiltinToken::CByte),
    ("ccur", BuiltinToken::CCur),
    ("hex", BuiltinToken::Hex),
    ("oct", BuiltinToken::Oct),
    // 字符串函数
    ("len", BuiltinToken::Len),
    ("trim", BuiltinToken::Trim),
    ("ltrim", BuiltinToken::LTrim),
    ("rtrim", BuiltinToken::RTrim),
    ("left", BuiltinToken::Left),
    ("right", BuiltinToken::Right),
    ("mid", BuiltinToken::Mid),
    ("ucase", BuiltinToken::UCase),
    ("lcase", BuiltinToken::LCase),
    ("instr", BuiltinToken::InStr),
    ("instrrev", BuiltinToken::InStrRev),
    ("strcomp", BuiltinToken::StrComp),
    ("replace", BuiltinToken::Replace),
    ("split", BuiltinToken::Split),
    ("join", BuiltinToken::Join),
    ("strreverse", BuiltinToken::StrReverse),
    ("space", BuiltinToken::Space),
    ("string", BuiltinToken::String_),
    ("asc", BuiltinToken::Asc),
    ("chr", BuiltinToken::Chr),
    ("ascw", BuiltinToken::AscW),
    ("chrw", BuiltinToken::ChrW),
    ("lenb", BuiltinToken::LenB),
    ("leftb", BuiltinToken::LeftB),
    ("rightb", BuiltinToken::RightB),
    ("midb", BuiltinToken::MidB),
    ("instrb", BuiltinToken::InStrB),
    ("ascb", BuiltinToken::AscB),
    ("chrb", BuiltinToken::ChrB),
    // 日期时间函数
    ("now", BuiltinToken::Now),
    ("date", BuiltinToken::Date),
    ("time", BuiltinToken::Time),
    ("year", BuiltinToken::Year),
    ("month", BuiltinToken::Month),
    ("day", BuiltinToken::Day),
    ("hour", BuiltinToken::Hour),
    ("minute", BuiltinToken::Minute),
    ("second", BuiltinToken::Second),
    ("weekday", BuiltinToken::WeekDay),
    ("dateadd", BuiltinToken::DateAdd),
    ("datediff", BuiltinToken::DateDiff),
    ("datepart", BuiltinToken::DatePart),
    ("dateserial", BuiltinToken::DateSerial),
    ("datevalue", BuiltinToken::DateValue),
    ("timeserial", BuiltinToken::TimeSerial),
    ("timevalue", BuiltinToken::TimeValue),
    ("formatdatetime", BuiltinToken::FormatDateTime),
    ("monthname", BuiltinToken::MonthName),
    ("weekdayname", BuiltinToken::WeekDayName),
    ("timer", BuiltinToken::Timer),
    // 数组函数
    ("array", BuiltinToken::Array),
    ("ubound", BuiltinToken::UBound),
    ("lbound", BuiltinToken::LBound),
    ("filter", BuiltinToken::Filter),
    ("isarray", BuiltinToken::IsArray),
    // 检验函数
    ("isnumeric", BuiltinToken::IsNumeric),
    ("isdate", BuiltinToken::IsDate),
    ("isempty", BuiltinToken::IsEmpty),
    ("isnull", BuiltinToken::IsNull),
    ("isobject", BuiltinToken::IsObject),
    ("isnothing", BuiltinToken::IsNothing),
    ("typename", BuiltinToken::TypeName),
    ("vartype", BuiltinToken::VarType),
    // 交互函数
    ("msgbox", BuiltinToken::MsgBox),
    ("inputbox", BuiltinToken::InputBox),
    // 其他函数
    ("createobject", BuiltinToken::CreateObject),
    ("getobject", BuiltinToken::GetObject),
    ("eval", BuiltinToken::Eval),
    ("execute", BuiltinToken::Execute),
    ("rgb", BuiltinToken::RGB),
    ("formatcurrency", BuiltinToken::FormatCurrency),
    ("formatnumber", BuiltinToken::FormatNumber),
    ("formatpercent", BuiltinToken::FormatPercent),
    ("scriptengine", BuiltinToken::ScriptEngine),
    (
        "scriptenginemajorversion",
        BuiltinToken::ScriptEngineMajorVersion,
    ),
    (
        "scriptengineminorversion",
        BuiltinToken::ScriptEngineMinorVersion,
    ),
    (
        "scriptenginebuildversion",
        BuiltinToken::ScriptEngineBuildVersion,
    ),
    ("erase", BuiltinToken::Erase),
    ("escape", BuiltinToken::Escape),
    ("unescape", BuiltinToken::Unescape),
    ("iif", BuiltinToken::IIf),
];
